trigger:
- main

pool:
  name: azure pipelines

steps:
- task: npm@01
    displayname: 'run npm install'
    command: npm install

- script: './node_modules/bin/node_saas Tailspin.spacegame.web/wwwroot --output Tailspin.spacegame.web/wwwroot'
    displayname: 'compile saas assets'

- task: gulp@01
    displayname: 'run gulp tasks'

- script: 'echo "$(build.definitionname), $(build.id), $(build.buildnumber)" > buildinfo.text'
    displayname: 'write build info'
    Workingdirectory: 'Tailspin.spaceweb.game/wwwroot'

-  task: dotnetcorecli@2
     displayname: 'restore project dependencies'
   inputs: 
     commands: 'restore'
     projects: '**/*.csproj'

-  task: dotnetcorecli@2
     displayname: 'build project'
   inputs: 
     commands: 'build'
     arguments: '--no-restore --configuration release'
     projects: '**/*.csproj'   

    